name: KysPlugin
main: de.sxlverc.kysplugin.Kysplugin
version: '1.0'
api-version: '1.21.1'
commands:
  kys:
    description: Executes the Kys command
  kyssetting:
    description: Configures the Kys settings